Repository ericberglund117/Refactor-tractor-WC-EB-KM-CD, pull requests merged in 2020-09, with the labels that each got.

#38 Cd sprint 1 functionality
  README.md
  test/recipe-test.js
  test/user-test.js
Labels: Refactor, TDD/Testing, enhancement

#65 Eb sprint 1 functionality
  src/recipe.js
  src/user.js
  test/recipe-test.js
  test/user-test.js
Labels: Refactor, TDD/Testing, bug, documentation

#67 Make filterRecipes method in user class dynamic to filter recipesToCo…
  src/.DS_Store
  src/user.js
  test/user-test.js
Labels: Refactor, TDD/Testing, enhancement

#66 Eb sprint 1 functionality2
  src/recipe.js
  test/recipe-test.js
Labels: Refactor, TDD/Testing, enhancement

#69 Km sprint 1 functionality
  README.md
  src/pantry.js
  test/pantry-test.js
Labels: Setup, TDD/Testing, documentation, enhancement

#70 Eb sprint 2 fetch
  package-lock.json
  package.json
  src/index.html
  src/scripts.js
Labels: Refactor, bug, enhancement, help wanted

#71 Cd sprint 2 fetch
  src/scripts.js
Labels: Refactor, bug, enhancement

#72 Km sprint 2 fetch
  src/scripts.js
Labels: Refactor, enhancement

#73 Eb sprint 2 fetch pantry
  src/pantry.js
  src/recipe.js
  src/user.js
  test/pantry-test.js
  test/recipe-test.js
  test/user-test.js
Labels: Refactor, TDD/Testing, bug

#74 Eb sprint 2 fetch pantry
  src/css/styles.scss
  src/index.html
  src/scripts.js
  src/user.js
Labels: Refactor, enhancement

#75 Cd sprint 3 dom updates
  src/domUpdates.js
  src/scripts.js
  test/domUpdates-test.js
Labels: DOM, Refactor, Server/Data, UI/UX sass/css/html, bug

#76 Km sprint 3 dom spies
  src/domUpdates.js
  src/scripts.js
  src/user.js
  test/domUpdates-test.js
  test/user-test.js
Labels: DOM, TDD/Testing, bug

#79 Eb sprint 4 sass
  src/css/mixins.scss
  src/css/styles.scss
  src/css/variables.scss
Labels: Refactor, UI/UX sass/css/html, enhancement

#78 Km sprint 3 organize and lint
  test/domUpdates-test.js
  test/recipe-test.js
  test/user-test.js
Labels: Refactor, TDD/Testing

#80 Cd sprint 4 scripts refactor
  src/.DS_Store
  src/css/styles.scss
  src/domUpdates.js
  src/scripts.js
Labels: DOM, Refactor, Server/Data, UI/UX sass/css/html, bug

#81 Km sprint 4 organize and lint
  src/domUpdates.js
  src/recipe.js
  src/scripts.js
  src/user.js
  test/recipe-test.js
Labels: Refactor, TDD/Testing, enhancement

#82 Eb sprint 5 responsiveness
  src/css/styles.scss
  src/css/variables.scss
  src/index.html
Labels: Accessibility, Refactor, UI/UX sass/css/html, bug

#83 Km sprint 6 final refactor
  README.md
  src/domUpdates.js
  src/images/RTWCAppJourney.gif
  src/images/RTWCAppMainPage.png
  src/images/RTWCAppMyRecipesView.png
  src/images/RTWCAppPantryMenu.png
  src/images/RTWCAppPantryModPopup.png
  src/images/RTWCAppRecipeInstructions.png
  src/images/RTWCAppRecipeSearch.png
  src/images/RTWCAppRecipeTypeSort.png
  src/recipe.js
  src/scripts.js
  test/recipe-test.js
Labels: DOM, Refactor, documentation, enhancement
